name: Destroy Ephemeral

on:
  delete:
    branches-ignore:
      - main
      - alpha
      - beta

jobs:
  destroy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up node
      uses: meza/action-setup-node-npm@main
      with:
        node-version: latest
        cache-name: destroy-${{ github.ref_name }}
    - name: 📦 Destroy ${{ github.ref_name }}
      run: npx cdk destroy remix-trance-stack-ephemeral --require-approval never --context environmentName=${{ github.ref_name }}
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
