name: Destroy Ephemeral

on:
  delete:
    branches-ignore:
      - main
      - alpha
      - beta

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  destroy:
    name: Destroy ${{ github.event.ref }} from an ephemeral environment
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - uses: actions/checkout@v3
    - name: Set up node
      uses: meza/action-setup-node-npm@main
      with:
        node-version: latest
        cache-name: destroy-${{ github.ref_name }}
    - name: 🔨 Build
      run: npm run build
      env:
        NODE_ENV: production
        SPLIT_SERVER_TOKEN: ${{ secrets.SPLIT_SERVER_TOKEN }}
        SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
        HOTJAR_ID: ${{ vars.HOTJAR_ID }}
        MIXPANEL_API: ${{ vars.MIXPANEL_API }}
        MIXPANEL_TOKEN: ${{ vars.MIXPANEL_TOKEN }}
        COOKIEYES_TOKEN: ${{ vars.COOKIEYES_TOKEN }}
        I18N_DEBUG: 'true'
        SPLIT_DEBUG: 'true'
    - name: 📦 Destroy ${{ github.ref_name }}
      run: npx cdk destroy remix-trance-stack-ephemeral --force --require-approval never --context environmentName=${{ github.ref_name }} --context domainName=${{ vars.AWS_DOMAIN_NAME }} --context certificateArn=${{ secrets.AWS_CERT_ARN }} --context hostedZoneName=${{ vars.AWS_HOSTED_ZONE_NAME }}
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
