name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    name: "Playwright Tests"
    timeout-minutes: 60
    runs-on: ubuntu-latest
    environment: playwright
    steps:
    - uses: actions/checkout@v3
    - name: Set up node
      uses: meza/action-setup-node-pnpm@main
      with:
        node-version: latest
        cache-name: 'playwright'
    - name: Install dependencies
      run: pnpm install
    - name: Create envfile
      uses: SpicyPizza/create-envfile@v1.3
      with:
        envkey_NODE_ENV: development
        envkey_HOTJAR_ID: ${{ secrets.HOTJAR_ID }}
        envkey_SPLIT_SERVER_TOKEN: ${{ secrets.SPLIT_SERVER_TOKEN }}
        envkey_MIXPANEL_API: ${{ env.MIXPANEL_API }}
        envkey_MIXPANEL_TOKEN: ${{ secrets.MIXPANEL_TOKEN }}
        envkey_SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
        envkey_COOKIEYES_TOKEN: ${{ secrets.COOKIEYES_TOKEN }}
    - name: Build
      run: pnpm build
    - name: Install Playwright Browsers
      run: pnpm exec playwright install --with-deps
    - name: Run Playwright tests
      run: DEBUG=pw:webserver pnpm int
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
